
# default:
#   outputs:
#     default:
#       type: snowflake
#       threads: 1
#       account: "{{ env_var('SF_DEV_ACCOUNT') }}"
#       user: "{{ env_var('SF_DEV_USERNAME') }}"
#       password: "{{ env_var('SF_DEV_PASSWORD') }}"
#       role: ACCOUNTADMIN
#       database: DEV
#       warehouse: COMPUTE_WH
#       schema: REPORT
#       client_session_keep_alive: False
#       query_tag: github_action_query


snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_DEV_ACCOUNT') }}"
      user: "{{ env_var('SF_DEV_USERNAME') }}"
      password: "{{ env_var('SF_DEV_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: DEV
      warehouse: COMPUTE_WH
      schema: REPORT
      client_session_keep_alive: False

    pre:
      type: snowflake
      account: "{{ env_var('SF_PRE_ACCOUNT') }}"
      user: "{{ env_var('SF_PRE_USERNAME') }}"
      password: "{{ env_var('SF_PRE_PASSWORD') }}"
      role: SYSADMIN
      database: "{{ env_var('SF_PRE_DATABASE') }}"
      warehouse: "{{ env_var('SF_PRE_WAREHOUSE') }}"
      schema: REPORT
      client_session_keep_alive: False
