name: test_run

on:
  push:
  pull_request:
    branches: [ "dev_branch" ]
env:
  DBT_PROFILES_DIR: ./
  SF_DEV_ACCOUNT: ${{ secrets.SF_DEV_ACCOUNT }}
  SF_DEV_USERNAME: ${{ secrets.SF_DEV_USERNAME }}
  SF_DEV_PASSWORD: ${{ secrets.SF_DEV_PASSWORD }}
  SF_PRE_ACCOUNT: ${{ secrets.SF_PRE_ACCOUNT }}
  SF_PRE_USERNAME: ${{ secrets.SF_PRE_USERNAME }}
  SF_PRE_PASSWORD: ${{ secrets.SF_PRE_PASSWORD }}
  SF_PRE_DATABASE: ${{ secrets.SF_PRE_DATABASE }}
  SF_PRE_WAREHOUSE: ${{ secrets.SF_PRE_WAREHOUSE }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@master
        
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"   
         
      - name: Install dependencies
        run: |
         pip install dbt-snowflake
         dbt deps   
      
      - name: Run dbt models
        run: dbt run   
        
      - name: Test dbt models
        run: dbt test
        
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python 3.8
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.8"
        
#       - name: Install dependecies
#         run: |
#           python -m pip install --upgrade pip

#       - name: Install dependencies
#         run: |
#           pip install dbt-snowflake
#           dbt deps
        
#       - name: Run dbt models
#         env:
#           SF_DEV_ACCOUNT: ${{ secrets.SF_DEV_ACCOUNT }}
#           SF_DEV_USERNAME: ${{ secrets.SF_DEV_USERNAME }}
#           SF_DEV_PASSWORD: ${{ secrets.SF_DEV_PASSWORD }}
#         run: dbt run

#       - name: Test dbt models
#         run: dbt test    

